Repository AICoE/idh-manifests, pull requests merged in 2020-11, with the labels that each got.

#32 Presto
  presto/.sops.yaml
  presto/README.md
  presto/base/aws-secret.yaml
  presto/base/kustomization.yaml
  presto/base/operator-group.yaml
  presto/base/presto-cr.yaml
  presto/base/subscription.yaml
  presto/overlays/dev/aws-secret.enc.yaml
  presto/overlays/dev/kustomization.yaml
  presto/overlays/dev/operator-group.yaml
  presto/overlays/dev/secret-generator.yaml
Labels: approved, size/L

#34 Update pytorch image to 0.0.2 release
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: size/XS

#35 Fix selectors in DC data catalog
  data-catalog/base/hue/hue-dc.yaml
  data-catalog/base/hue/hue-mysql-dc.yaml
  data-catalog/base/hue/hue-mysql-service.yaml
  data-catalog/base/hue/hue-service.yaml
  data-catalog/base/thriftserver/postgres-dc.yaml
  data-catalog/base/thriftserver/postgres-service.yaml
  data-catalog/base/thriftserver/thriftserver-dc.yaml
  data-catalog/base/thriftserver/thriftserver-service.yaml
Labels: size/S

#36 Fix selectors in data catalog again
  data-catalog/base/hue/hue-mysql-dc.yaml
  data-catalog/base/hue/hue-mysql-service.yaml
  data-catalog/base/thriftserver/kustomization.yaml
  data-catalog/base/thriftserver/postgres-dc.yaml
  data-catalog/base/thriftserver/postgres-service.yaml
Labels: size/S

#37 Add Thoth Devops key
  OWNERS
  kafka/.sops.yaml
  kafka/secrets.enc.yaml
Labels: approved, do-not-merge/invalid-owners-file, size/L

#38 Update categorical encoding image link
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: approved, size/XS

#40 Add GPU Pytorch Image
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: do-not-merge/invalid-owners-file, size/M

#39 Add rolebinding for the argocd-manager SA to deploy to the namespace and add apiGroups
  data-catalog/base/argocd-rb.yaml
  data-catalog/base/hue/hue-dc.yaml
  data-catalog/base/hue/hue-mysql-dc.yaml
  data-catalog/base/hue/hue-route.yaml
  data-catalog/base/thriftserver/postgres-dc.yaml
  data-catalog/base/thriftserver/thriftserver-custom-authenticator-is.yaml
  data-catalog/base/thriftserver/thriftserver-dc.yaml
  data-catalog/base/thriftserver/thriftserver-route.yaml
Labels: approved, size/S

#41 Remove duplicate Tensorflow build-config
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: approved, size/M

#42 Fix DeploymentConfig api group in patches and commonlabels propagation
  data-catalog/base/hue/kustomization.yaml
  data-catalog/base/kustomization.yaml
  data-catalog/base/thriftserver/kustomization.yaml
  data-catalog/overlays/prod/hue/hue-dc.yaml
Labels: approved, size/S

#43 Remove common-labels
  data-catalog/base/hue/kustomization.yaml
  data-catalog/base/thriftserver/kustomization.yaml
Labels: approved, size/S

#44 Fetch the container images from quay.io instead of docker
  data-catalog/base/hue/kustomization.yaml
  data-catalog/base/thriftserver/kustomization.yaml
Labels: approved, size/XS

#46 Increase the initialDelay for mysql readiness probe
  data-catalog/base/hue/hue-mysql-dc.yaml
Labels: approved, size/XS

#45 Change stage data-catalog aws credentials to match prod
  data-catalog/overlays/stage/hue/hue-ini-secret.enc.yaml
Labels: approved, size/XS

#47 Update all stage AWS credentials to match prod and update PVC to use current PVC names and claims
  data-catalog/base/hue/hue-mysql-dc.yaml
  data-catalog/base/hue/hue-mysql-pvc.yaml
  data-catalog/base/thriftserver/postgres-dc.yaml
  data-catalog/base/thriftserver/postgres-pvc.yaml
  data-catalog/base/thriftserver/thriftserver-dc.yaml
  data-catalog/overlays/prod-ccx/hue/hue-mysql-pvc.yaml
  data-catalog/overlays/prod-ccx/thriftserver/postgres-pvc.yaml
  data-catalog/overlays/prod-customer-journeys/hue/hue-mysql-pvc.yaml
  data-catalog/overlays/prod-customer-journeys/thriftserver/postgres-pvc.yaml
  data-catalog/overlays/prod-usir/hue/hue-mysql-pvc.yaml
  data-catalog/overlays/prod-usir/thriftserver/postgres-pvc.yaml
  data-catalog/overlays/prod/hue/hue-mysql-pvc.yaml
  data-catalog/overlays/prod/thriftserver/postgres-pvc.yaml
  data-catalog/overlays/stage/hue/hive-site-xml-secret.enc.yaml
  data-catalog/overlays/stage/hue/hue-mysql-pvc.yaml
  data-catalog/overlays/stage/hue/hue-secret.enc.yaml
  data-catalog/overlays/stage/thriftserver/postgres-pvc.yaml
  data-catalog/overlays/stage/thriftserver/thriftserver-secret.enc.yaml
Labels: approved, size/M

#48 Update USIR and CCX creds to match prod.
  data-catalog/overlays/prod-ccx/hue/hive-site-xml-secret.enc.yaml
  data-catalog/overlays/prod-usir/hue/hive-site-xml-secret.enc.yaml
Labels: approved, size/S

#49 Change the resource limits from strategicMerge to JSON patch
  data-catalog/overlays/prod/hue/hue-dc.yaml
  data-catalog/overlays/prod/hue/hue_dc_patch.json
  data-catalog/overlays/prod/hue/kustomization.yaml
Labels: approved, size/M
