Repository AICoE/idh-manifests, pull requests merged in 2020-10, with the labels that each got.

#13 Default workflow settings for aiops-prod-argo
  argo/overlays/aiops-prod-argo/kustomization.yaml
  argo/overlays/aiops-prod-argo/workflow-controller-configmap.yaml
Labels: approved, size/S

#12 Update argo to 2.11.1
  argo/base/argo-user-role.yaml
  argo/base/kustomization.yaml
  argo/base/workflow-controller-configmap.yaml
Labels: approved, size/S

#16 Fix monitoring route termination typo
  monitoring/psi-prod-cluster/bases/alertmanager/oauth/route.yaml
  monitoring/psi-prod-cluster/bases/prometheus/oauth/route.yaml
Labels: approved, size/XS

#17 Add argocd scrape config
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  monitoring/psi-prod-cluster/bases/prometheus/prometheus.yaml
  monitoring/psi-prod-cluster/overlays/prod/configs/additional-scrape-configs.yaml
  monitoring/psi-prod-cluster/overlays/prod/kustomization.yaml
  monitoring/psi-prod-cluster/overlays/prod/prometheus.yaml
Labels: approved, size/M

#18 Updated dh-psi-monitoring service monitor configurations
  aicoe-argocd/bases/servicemonitor/aicoe-argocd-monitor.yaml
  monitoring/psi-prod-cluster/README.md
  monitoring/psi-prod-cluster/bases/alertmanager/alertmanager.yaml
  monitoring/psi-prod-cluster/bases/prometheus/prometheus.yaml
  monitoring/psi-prod-cluster/overlays/prod/configs/additional-scrape-configs.yaml
Labels: approved, size/S

#21 Adding cnv-qe-testing topic
  kafka/secrets.enc.yaml
Labels: approved, size/L

#20 Add custom profile for shanand user and reorder custom profiles
  jupyterhub/bases/custom-profiles/jupyterhub-singleuser-profiles.yaml
Labels: approved, size/L

#14 added new ImageStream entry for insights configuration file analysis
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: approved, size/S

#22 Add kafka topic for expunge
  kafka/secrets.enc.yaml
Labels: approved, size/L

#23 Update path for the kafka repo
  kafka/secrets.enc.yaml
Labels: approved, size/M

#25 Updating ownership
  OWNERS
Labels: size/XS

#24 added new ImageStream entry for configuration file analysis
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: size/S

#28 Add test image for Spark 3.0.0 notebook
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: approved, size/S

#26 Fix pre-commit errors
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
  kafka/README.md
Labels: approved, do-not-merge/hold, size/S

#30 Increase partition count for topic ccx-dev-insights-operator-archive-features
  kafka/secrets.enc.yaml
Labels: approved, size/L

#31 include s2i-pytorch-notebook image to idh imagestreams
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: approved, size/S
