Repository AICoE/idh-manifests, pull requests merged in 2020-12, with the labels that each got.

#50 Add s2i-minimal-notebook-gpu buildconfig for management by ArgoCD
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: approved, size/M

#51 Add superset
  .gitignore
  superset/.sops.yaml
  superset/Chart.yaml
  superset/README.md
  superset/helm_vars/dev/secrets.yaml
  superset/helm_vars/dev/values.yaml
  superset/helm_vars/prod/secrets.yaml
  superset/helm_vars/prod/values.yaml
  superset/helm_vars/stage/secrets.yaml
  superset/helm_vars/stage/values.yaml
  superset/secrets.enc.yaml
  superset/superset/argocd-manager-rolebinding.yaml
  superset/templates/odh_cr.yaml
Labels: approved, size/L

#52 Fix Superset Template
  superset/superset/argocd-manager-rolebinding.yaml
  superset/templates/odh_cr.yaml
Labels: approved, size/S

#53 Keep different Superset PostgreSQL passwords based on environment
  superset/helm_vars/dev/secrets.yaml
  superset/helm_vars/prod/secrets.yaml
  superset/helm_vars/stage/secrets.yaml
  superset/secrets.enc.yaml
Labels: approved, size/S

#54 Update endpoint for the thriftserver liveness probe
  data-catalog/base/thriftserver/thriftserver-dc.yaml
Labels: approved, size/XS

#55 Downgrade argo 2.11.1 -> 2.11.0
  argo/base/kustomization.yaml
Labels: approved, size/S

#59 Change all Data Catalog instances to point to a single spark cluster
  data-catalog/overlays/prod-ccx/thriftserver/thriftserver-server-conf-secret.enc.yaml
  data-catalog/overlays/prod-customer-journeys/thriftserver/thriftserver-server-conf-secret.enc.yaml
  data-catalog/overlays/prod-usir/thriftserver/thriftserver-server-conf-secret.enc.yaml
Labels: approved, size/M

#61 Remove dh-prod-customer-journeys Data Catalog
  data-catalog/overlays/prod-customer-journeys/hue/hive-site-xml-secret.enc.yaml
  data-catalog/overlays/prod-customer-journeys/hue/hue-ini-secret.enc.yaml
  data-catalog/overlays/prod-customer-journeys/hue/hue-mysql-pvc.yaml
  data-catalog/overlays/prod-customer-journeys/hue/hue-mysql-secret.enc.yaml
  data-catalog/overlays/prod-customer-journeys/hue/hue-secret.enc.yaml
  data-catalog/overlays/prod-customer-journeys/hue/kustomization.yaml
  data-catalog/overlays/prod-customer-journeys/hue/secret-generator.yaml
  data-catalog/overlays/prod-customer-journeys/kustomization.yaml
  data-catalog/overlays/prod-customer-journeys/thriftserver/kustomization.yaml
  data-catalog/overlays/prod-customer-journeys/thriftserver/postgres-pvc.yaml
  data-catalog/overlays/prod-customer-journeys/thriftserver/postgres-secret.enc.yaml
  data-catalog/overlays/prod-customer-journeys/thriftserver/secret-generator.yaml
  data-catalog/overlays/prod-customer-journeys/thriftserver/thriftserver-custom-authenticator-secret.enc.yaml
  data-catalog/overlays/prod-customer-journeys/thriftserver/thriftserver-hdfs-hive-secret.enc.yaml
  data-catalog/overlays/prod-customer-journeys/thriftserver/thriftserver-pvc.yaml
  data-catalog/overlays/prod-customer-journeys/thriftserver/thriftserver-secret.enc.yaml
  data-catalog/overlays/prod-customer-journeys/thriftserver/thriftserver-server-conf-secret.enc.yaml
Labels: approved, size/L

#60 Remove Kafka Connect Artifacts
  kafka/custom-connect-image/Dockerfile
  kafka/helm_vars/dev/secrets.yaml
  kafka/helm_vars/dev/values.yaml
  kafka/helm_vars/prod/secrets.yaml
  kafka/helm_vars/prod/values.yaml
  kafka/helm_vars/stage/secrets.yaml
  kafka/helm_vars/stage/values.yaml
  kafka/kafka-connector-manager/Dockerfile
  kafka/kafka-connector-manager/connector_manager.py
  kafka/kafka-connector-manager/requirements.txt
  kafka/templates/kafka-connect.yaml
Labels: approved, size/L

#64 Use external hostname for spark in thriftserver instances
  data-catalog/overlays/prod-ccx/thriftserver/thriftserver-server-conf-secret.enc.yaml
  data-catalog/overlays/prod-usir/thriftserver/thriftserver-server-conf-secret.enc.yaml
Labels: approved, size/M

#65 Use wildcard routes for spark clusters
  data-catalog/overlays/prod-ccx/thriftserver/thriftserver-server-conf-secret.enc.yaml
  data-catalog/overlays/prod-usir/thriftserver/thriftserver-server-conf-secret.enc.yaml
Labels: approved, size/M

#58 Set proper timeouts for Hue
  data-catalog/base/hue/hue-ini-secret.yaml
  data-catalog/base/hue/hue-route.yaml
  data-catalog/overlays/dev/hue/hue-ini-secret.enc.yaml
  data-catalog/overlays/prod-ccx/hue/hue-ini-secret.enc.yaml
  data-catalog/overlays/prod-usir/hue/hue-ini-secret.enc.yaml
  data-catalog/overlays/prod/hue/hue-ini-secret.enc.yaml
  data-catalog/overlays/stage/hue/hue-ini-secret.enc.yaml
Labels: approved, size/L
