Repository AICoE/idh-manifests, pull requests merged in 2021-02, with the labels that each got.

#85 Update presto artifacts to match latest deployment
  presto/base/kustomization.yaml
  presto/base/postgres-dc.yaml
  presto/base/postgres-pvc.yaml
  presto/base/postgres-secret.yaml
  presto/base/postgres-service.yaml
  presto/base/presto-cr.yaml
Labels: approved, size/L

#86 Add MySQL exporter secret to production environment
  data-catalog/overlays/prod/hue/hue-mysqld-exporter-secret.enc.yaml
  data-catalog/overlays/prod/hue/secret-generator.yaml
Labels: approved, size/M

#87 Add new kafka topic for PNC
  kafka/secrets.enc.yaml
Labels: approved, size/L

#89 Add Thanos Extractor argo overlays
  argo-events/overlays/dh-prod-thanos-extractor/kustomization.yaml
  argo-events/overlays/dh-prod-thanos-extractor/membership.yaml
  argo/overlays/dh-prod-thanos-extractor/kustomization.yaml
  argo/overlays/dh-prod-thanos-extractor/membership.yaml
Labels: approved, size/L

#90 Set proper resource requests and limits for Hue database
  data-catalog/base/hue/hue-mysql-dc.yaml
Labels: approved, size/XS

#91 Bump up hue PVC size
  data-catalog/base/hue/hue-mysql-pvc.yaml
Labels: approved, size/XS

#92 Bump up thriftserver PVC size
  data-catalog/base/thriftserver/postgres-pvc.yaml
Labels: approved, size/XS

#93 Add Node Selectors for Thanos Extractor Argo pods
  argo/overlays/dh-prod-thanos-extractor/deployments/argo-server_patch.yaml
  argo/overlays/dh-prod-thanos-extractor/deployments/workflow-controller_patch.yaml
  argo/overlays/dh-prod-thanos-extractor/kustomization.yaml
Labels: approved, size/S

#94 Add the Kafka exporter
  kafka/templates/kafka-cluster.yaml
Labels: approved, size/XS

#96 Tune the thresholds for the Thriftserver liveness probe
  data-catalog/base/thriftserver/thriftserver-dc.yaml
Labels: approved, size/XS

#97 Revert "Bump up thriftserver PVC size"
  data-catalog/base/thriftserver/postgres-pvc.yaml
Labels: approved, size/XS

#98 Remove the data catalog mysql exporter
  data-catalog/base/hue/hue-mysql-dc.yaml
  data-catalog/base/hue/hue-mysqld-exporter-secret.yaml
  data-catalog/base/hue/kustomization.yaml
  data-catalog/overlays/prod/hue/hue-mysqld-exporter-secret.enc.yaml
  data-catalog/overlays/prod/hue/secret-generator.yaml
Labels: approved, size/M

#99 Remove capabilities dict from data catalog deployment configs
  data-catalog/base/hue/hue-mysql-dc.yaml
  data-catalog/base/thriftserver/postgres-dc.yaml
Labels: approved, size/XS

#100 Update dh-prod-argo argo-events
  argo-events/base/kustomization.yaml
  argo-events/overlays/dh-prod-argo/membership.yaml
  argo-events/overlays/dh-prod-thanos-extractor/kustomization.yaml
  argo-events/overlays/dh-prod-thanos-extractor/membership.yaml
Labels: approved, size/M

#101 Remove tls-acme annotation from JupyterHub route
  jupyterhub/overlays/prod/jupyterhub-route.enc.yaml
Labels: approved, size/M

#95 Fix Presto Hive Metastore JDBC URL
  presto/base/presto-cr.yaml
  presto/overlays/dev/kustomization.yaml
  presto/overlays/dev/presto-cr.yaml
Labels: approved, size/S

#102 Revert back USIR Data Catalog to use its own spark cluster
  data-catalog/overlays/prod-usir/thriftserver/thriftserver-server-conf-secret.enc.yaml
Labels: approved, size/S

#103 Clean up owners
  OWNERS
Labels: approved, lgtm, size/S

#104 Add Kustomize Build Test Script
  test-kustomize-build
Labels: approved, lgtm, size/S
