Repository AICoE/idh-manifests, pull requests merged in 2021-01, with the labels that each got.

#66 Add kafkatopic
  kafka/secrets.enc.yaml
Labels: approved, size/M

#63 Update jupyterhub config to enable hostIPC access for select users
  jupyterhub/bases/custom-profiles/jupyterhub-singleuser-profiles.yaml
  jupyterhub/bases/jupyterhub/configs/jupyterhub_config.py
Labels: approved, do-not-merge/hold, size/S

#68 Add serviceAccount that has been attached to the dh-restricted scc
  jupyterhub/bases/jupyterhub/configs/jupyterhub_config.py
  jupyterhub/bases/jupyterhub/jupyterhub-host-ipc-sa.yaml
  jupyterhub/bases/jupyterhub/kustomization.yaml
Labels: approved, size/S

#67 Set app label in all Data Catalog objects
  data-catalog/base/hue/hive-site-xml-secret.yaml
  data-catalog/base/hue/hue-db-init-job.yaml
  data-catalog/base/hue/hue-dc.yaml
  data-catalog/base/hue/hue-ini-secret.yaml
  data-catalog/base/hue/hue-mysql-dc.yaml
  data-catalog/base/hue/hue-mysql-pvc.yaml
  data-catalog/base/hue/hue-mysql-secret.yaml
  data-catalog/base/hue/hue-mysql-service.yaml
  data-catalog/base/hue/hue-mysqld-exporter-secret.yaml
  data-catalog/base/hue/hue-route.yaml
  data-catalog/base/hue/hue-secret.yaml
  data-catalog/base/hue/hue-service.yaml
  data-catalog/base/thriftserver/postgres-dc.yaml
  data-catalog/base/thriftserver/postgres-exporter.yaml
  data-catalog/base/thriftserver/postgres-pvc.yaml
  data-catalog/base/thriftserver/postgres-secret.yaml
  data-catalog/base/thriftserver/postgres-service.yaml
  data-catalog/base/thriftserver/thriftserver-custom-authenticator-bc.yaml
  data-catalog/base/thriftserver/thriftserver-custom-authenticator-is.yaml
  data-catalog/base/thriftserver/thriftserver-custom-authenticator-secret.yaml
  data-catalog/base/thriftserver/thriftserver-dc.yaml
  data-catalog/base/thriftserver/thriftserver-hdfs-hive-secret.yaml
  data-catalog/base/thriftserver/thriftserver-pvc.yaml
  data-catalog/base/thriftserver/thriftserver-route.yaml
  data-catalog/base/thriftserver/thriftserver-secret.yaml
  data-catalog/base/thriftserver/thriftserver-server-conf-secret.yaml
  data-catalog/base/thriftserver/thriftserver-service.yaml
Labels: approved, size/M

#69 Change Thrift Server configuration to add JVM tunning per environment
  data-catalog/overlays/dev/thriftserver/thriftserver-server-conf-secret.enc.yaml
  data-catalog/overlays/prod-ccx/thriftserver/thriftserver-server-conf-secret.enc.yaml
  data-catalog/overlays/prod-usir/thriftserver/thriftserver-server-conf-secret.enc.yaml
  data-catalog/overlays/prod/thriftserver/thriftserver-server-conf-secret.enc.yaml
  data-catalog/overlays/stage/thriftserver/thriftserver-server-conf-secret.enc.yaml
Labels: approved, size/L

#70 Add node affinity for don's JH pods so that they land on the v100 GPUs
  jupyterhub/bases/custom-profiles/jupyterhub-singleuser-profiles.yaml
Labels: approved, size/XS

#62 feat: Upgrade Argo to v2.12.3
  argo/base/kustomization.yaml
Labels: approved, size/S

#71 Upgrade superset to v0.38.0
  superset/secrets.enc.yaml
Labels: approved, size/XS

#72 Stop the db-init job from running during an upgrade
  superset/templates/odh_cr.yaml
Labels: approved, size/XS

#57 Update custom image for ocp4-anomaly-detection
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: approved, size/XS

#73 Update Owners
  OWNERS
Labels: approved, size/S

#74 Replace Node Selector for DH-STAGE-ARGO app
  argo/overlays/dh-stage-argo/deployments/argo-server_patch.yaml
  argo/overlays/dh-stage-argo/deployments/workflow-controller_patch.yaml
  argo/overlays/dh-stage-argo/kustomization.yaml
Labels: approved, size/S

#75 Move replace directive to correct location within argo patches
  argo/overlays/dh-stage-argo/deployments/argo-server_patch.yaml
  argo/overlays/dh-stage-argo/deployments/workflow-controller_patch.yaml
Labels: approved, size/XS

#76 Add NodeSelector patches for Prod Data Hub
  argo/overlays/dh-prod-argo/deployments/argo-server_patch.yaml
  argo/overlays/dh-prod-argo/deployments/workflow-controller_patch.yaml
  argo/overlays/dh-prod-argo/kustomization.yaml
Labels: approved, size/S

#78 Add resource limits for superset and its database
  superset/helm_vars/prod/values.yaml
  superset/helm_vars/stage/values.yaml
  superset/templates/odh_cr.yaml
Labels: approved, size/S

#77 feat: Update Argo to 2.12.5 and use upstream images again
  argo/base/kustomization.yaml
Labels: approved, size/S

#80 Add kafkatopic for assisted-service-events
  kafka/secrets.enc.yaml
Labels: approved, size/XS

#82 Set thriftserver to use 4 cores
  data-catalog/base/thriftserver/thriftserver-dc.yaml
Labels: approved, size/XS

#83 Set default TTL of 1 day for all workflows
  argo/base/workflow-controller-configmap.yaml
  argo/overlays/aiops-prod-argo/kustomization.yaml
  argo/overlays/aiops-prod-argo/workflow-controller-configmap.yaml
Labels: approved, size/S

#84 Increase hardware resources given to Hue
  data-catalog/base/hue/hue-dc.yaml
  data-catalog/overlays/prod/hue/hue_dc_patch.json
  data-catalog/overlays/prod/hue/kustomization.yaml
Labels: approved, size/M
