Repository AICoE/idh-manifests, pull requests merged in 2021-05, with the labels that each got.

#147 Change the base image for kafka consumer lag monitor s2i build
  kafka/templates/kafka-monitor.yaml
Labels: approved, lgtm, size/XS

#148 increase Trino CPU resources as recommended by Starburst
  trino/overlays/prod/kustomization.yaml
Labels: approved, lgtm, size/XS

#146 Increase retention of PNC topics
  kafka/secrets.enc.yaml
Labels: approved, lgtm, size/L

#145 feat: Remove Argo-Events
  argo-events/README.md
  argo-events/base/argo-events-user-role.yaml
  argo-events/base/kustomization.yaml
  argo-events/overlays/aiops-prod-argo/kustomization.yaml
  argo-events/overlays/aiops-prod-argo/membership.yaml
  argo-events/overlays/dh-dev-argo/kustomization.yaml
  argo-events/overlays/dh-prod-argo/kustomization.yaml
  argo-events/overlays/dh-prod-argo/membership.yaml
  argo-events/overlays/dh-stage-argo/kustomization.yaml
  argo-events/overlays/dh-stage-argo/membership.yaml
Labels: approved, lgtm, size/L

#149 LDAP mappings for superset
  superset/templates/odh_cr.yaml
Labels: approved, lgtm, size/S

#150 Add line breaks
  superset/templates/odh_cr.yaml
Labels: approved, lgtm, size/XS

#151 Update LDAP groups to check against
  superset/templates/odh_cr.yaml
Labels: approved, lgtm, size/XS

#152 Implement initial Access Control on Trino instances and cleanup Hive Metastore configmaps
  trino/base/hadoop-config.yaml
  trino/base/hive-config.yaml
  trino/base/hive-jmx-config.yaml
  trino/overlays/prod/trino-config-secret.yaml
  trino/overlays/prod/trino-coordinator-dc.yaml
  trino/overlays/stage/trino-config-secret.yaml
  trino/overlays/stage/trino-coordinator-dc.yaml
Labels: approved, size/L

#154 Remove the storage class for stage trino PVC
  trino/overlays/stage/trino-db-pvc.yaml
Labels: approved, lgtm, size/XS

#156 Set Trino to use its own readonly credentials in stage and prod
  trino/overlays/prod/aws-secret.enc.yaml
  trino/overlays/stage/aws-secret.enc.yaml
Labels: approved, lgtm, size/S

#157 Add grokket and product-marketing groups and set Access Control
  trino/base/trino-config-secret.yaml
  trino/base/trino-coordinator-dc.yaml
  trino/overlays/prod/kustomization.yaml
  trino/overlays/prod/trino-config-secret.yaml
  trino/overlays/prod/trino-coordinator-dc.yaml
  trino/overlays/stage/kustomization.yaml
  trino/overlays/stage/trino-config-secret.yaml
  trino/overlays/stage/trino-coordinator-dc.yaml
Labels: approved, lgtm, size/L

#158 Add file authenticator for service account creation
  trino/base/trino-config-secret.yaml
  trino/base/trino-coordinator-dc.yaml
Labels: approved, lgtm, size/S

#159 Add Trino prod friendly URL
  trino/overlays/prod/secret-generator.yaml
  trino/overlays/prod/trino-secure-route.enc.yaml
Labels: approved, lgtm, size/M

#160 Fix trino prod secret-generator
  trino/overlays/prod/secret-generator.yaml
Labels: approved, lgtm, size/XS

#161 Change superset image to support Trino integration
  superset/secrets.enc.yaml
Labels: approved, lgtm, size/XS
