Repository AICoE/idh-manifests, pull requests merged in 2021-06, with the labels that each got.

#162 Add openshift-community-enablement group (jfiala)
  trino/base/trino-config-secret.yaml
Labels: approved, lgtm, size/XS

#163 Add KNI QE Kafka Topic
  kafka/secrets.enc.yaml
Labels: approved, lgtm, size/M

#164 Update kafka storage class name for stage
  kafka/helm_vars/stage/values.yaml
Labels: approved, lgtm, size/XS

#165 Update storage class for stage zookeeper
  kafka/helm_vars/stage/values.yaml
Labels: approved, lgtm, size/XS

#166 Add new groups to access Trino environment
  trino/base/trino-config-secret.yaml
Labels: approved, lgtm, size/S

#167 Fix Trino ACL to give groups access to the catalog
  trino/base/trino-config-secret.yaml
Labels: approved, lgtm, size/XS

#168 Add KNI QE CI test and data Kafka Topics
  kafka/secrets.enc.yaml
Labels: approved, lgtm, size/XS

#169 Allow all groups to access system schema and increase prod Trino memory limits
  trino/base/trino-config-secret.yaml
  trino/overlays/prod/kustomization.yaml
Labels: approved, lgtm, size/XS

#170 Add ACM team to Trino access
  trino/base/trino-config-secret.yaml
Labels: approved, size/XS

#173 update the resource limit for the prowjobs
  .prow.yaml
  trino/base/hive-jmx-config.yaml
  trino/base/trino-config-secret.yaml
Labels: approved, lgtm, size/S

#172 Fix dev deployment of kafka
  kafka/README.md
  kafka/helm_vars/dev/values.yaml
Labels: approved, lgtm, size/S
