Repository AICoE/idh-manifests, pull requests merged in 2021-03, with the labels that each got.

#106 Replace .aicoe.yaml with .prow.yaml
  .aicoe-ci.yaml
  .prow.yaml
  test-kustomize-build
Labels: approved, lgtm, size/M

#105 feat: Add aicoe-ccx to aiops-prod-argo project
  argo/overlays/aiops-prod-argo/membership.yaml
Labels: approved, lgtm, size/S

#110 Add a login entry for IT EDA Data Governance team to access USIR Data
  data-catalog/overlays/prod-usir/thriftserver/thriftserver-custom-authenticator-secret.enc.yaml
Labels: approved, size/S

#107 Grant esammons and jeking edit access to dh-prod-argo
  argo/overlays/dh-prod-argo/membership.yaml
Labels: approved, lgtm, size/S

#111 Fix Argo edit role
  argo/overlays/dh-prod-argo/membership.yaml
Labels: approved, lgtm, size/XS

#113 Fix Java syntax in Thrift Server custom auth code
  data-catalog/overlays/prod-usir/thriftserver/thriftserver-custom-authenticator-secret.enc.yaml
Labels: approved, lgtm, size/XS

#114 Revert rsyslog topic name
  kafka/secrets.enc.yaml
Labels: approved, lgtm, size/L

#115 Revert "Revert rsyslog topic name"
  kafka/secrets.enc.yaml
Labels: approved, lgtm, size/L

#116 Add dynamic-rsyslog topic
  kafka/secrets.enc.yaml
Labels: approved, lgtm, size/L

#117 Remove dynamic-rsyslog-new topic
  kafka/secrets.enc.yaml
Labels: approved, lgtm, size/L

#118 Change kafka retention for ccx topics
  kafka/secrets.enc.yaml
Labels: approved, size/L

#119 Update spark config for ccx thriftserver
  data-catalog/overlays/prod-ccx/thriftserver/thriftserver-server-conf-secret.enc.yaml
Labels: approved, size/S

#120 Point CCX thriftserver at dedicated spark cluster
  data-catalog/overlays/prod-ccx/thriftserver/thriftserver-server-conf-secret.enc.yaml
Labels: approved, size/S

#121 Point ccx thriftserver at dedicated spark cluster
  data-catalog/overlays/prod-ccx/thriftserver/thriftserver-server-conf-secret.enc.yaml
Labels: approved, lgtm, size/S
