Repository AICoE/idh-manifests, pull requests merged in 2021-07, with the labels that each got.

#175 Fixed repo reference in argo workflow
  argo/README.md
  argo/base/kustomization.yaml
Labels: approved, lgtm, size/XS

#176 Update superset storage class for ocp4 dev clusters
  superset/helm_vars/dev/values.yaml
Labels: approved, size/XS

#177 Add special resources to esammons JH pod
  jupyterhub/bases/custom-profiles/jupyterhub-singleuser-profiles.yaml
Labels: lgtm, size/XS

#179 Grant the telemeter-auth group the Telemetry superset role
  superset/templates/odh_cr.yaml
Labels: approved, lgtm, size/XS

#178 Added lucferbux in the owner list
  OWNERS
Labels: approved, lgtm, size/XS

#180 Change CCX Thrift Server configuration to use more resources from Spa…
  data-catalog/overlays/prod-ccx/thriftserver/thriftserver-server-conf-secret.enc.yaml
Labels: approved, lgtm, size/XS
