Repository AICoE/idh-manifests, pull requests merged in 2021-04, with the labels that each got.

#122 Grand qe-ds group membership for argo and argo-events
  argo-events/overlays/dh-prod-argo/membership.yaml
  argo/overlays/dh-prod-argo/membership.yaml
Labels: approved, size/XS

#123 Update retention for dynamic-rsyslog
  kafka/secrets.enc.yaml
Labels: approved, lgtm, size/L

#124 Remove qe-ds membership for argo events
  argo-events/overlays/dh-prod-argo/membership.yaml
Labels: approved, size/XS

#125 Update retention for dynamic-rsyslog to 45Gi per partition
  kafka/secrets.enc.yaml
Labels: approved, lgtm, size/L

#126 Fix issues with the presto deployment
  presto/base/postgres-dc.yaml
  presto/base/presto-cr.yaml
Labels: approved, size/XS

#127 Update JupyterHub cert and key
  jupyterhub/overlays/prod/jupyterhub-route.enc.yaml
Labels: approved, lgtm, size/M

#128 Add bcourt user in USIR Data Catalog
  data-catalog/overlays/prod-usir/thriftserver/thriftserver-custom-authenticator-secret.enc.yaml
Labels: approved, lgtm, size/XS

#129 Add base Trino files to internal repo
  trino/README.md
  trino/base/aws-secret.yaml
  trino/base/hadoop-config.yaml
  trino/base/hive-config.yaml
  trino/base/hive-db-secret.yaml
  trino/base/hive-jmx-config.yaml
  trino/base/hive-metastore-dc.yaml
  trino/base/hive-metastore-entrypoint.yaml
  trino/base/hive-metastore-service.yaml
  trino/base/kustomization.yaml
  trino/base/params.env
  trino/base/params.yaml
  trino/base/trino-catalog-secret.yaml
  trino/base/trino-config-secret.yaml
  trino/base/trino-coordinator-dc.yaml
  trino/base/trino-db-dc.yaml
  trino/base/trino-db-pvc.yaml
  trino/base/trino-db-secret.yaml
  trino/base/trino-db-service.yaml
  trino/base/trino-route.yaml
  trino/base/trino-service.yaml
  trino/base/trino-worker-dc.yaml
  trino/overlays/storage-class/kustomization.yaml
  trino/overlays/storage-class/pvc-patch.yaml
Labels: approved, lgtm, size/XXL

#131 Add overlays for trino in dev and stage, parameterize variables in hive-metastore-dc
  trino/.sops.yaml
  trino/base/hive-metastore-dc.yaml
  trino/overlays/dev/aws-secret.enc.yaml
  trino/overlays/dev/kustomization.yaml
  trino/overlays/dev/secret-generator.yaml
  trino/overlays/stage/aws-secret.enc.yaml
  trino/overlays/stage/kustomization.yaml
  trino/overlays/stage/secret-generator.yaml
  trino/overlays/stage/trino-db-pvc.yaml
Labels: approved, lgtm, size/L

#132 Add trino prod overlay
  trino/overlays/prod/aws-secret.enc.yaml
  trino/overlays/prod/kustomization.yaml
  trino/overlays/prod/secret-generator.yaml
  trino/overlays/prod/trino-db-pvc.yaml
  trino/overlays/prod/trino-db-secret.enc.yaml
Labels: approved, lgtm, size/L

#133 Add LDAP authentication configuration in trino stage and prod
  trino/base/root-ca-secret.enc.yaml
  trino/base/trino-config-secret.yaml
  trino/base/trino-route.yaml
  trino/overlays/prod/hive-metastore-dc.yaml
  trino/overlays/prod/kustomization.yaml
  trino/overlays/prod/secret-generator.yaml
  trino/overlays/prod/trino-config-secret.yaml
  trino/overlays/prod/trino-coordinator-dc.yaml
  trino/overlays/stage/kustomization.yaml
  trino/overlays/stage/secret-generator.yaml
  trino/overlays/stage/trino-config-secret.yaml
  trino/overlays/stage/trino-coordinator-dc.yaml
Labels: approved, lgtm, size/L

#134 Fix stage and prod parameters
  trino/overlays/prod/kustomization.yaml
  trino/overlays/stage/kustomization.yaml
Labels: approved, size/XS

#135 Change AWS keys
  trino/overlays/prod/aws-secret.enc.yaml
Labels: approved, lgtm, size/S

#136 Change prod bucket
  trino/overlays/prod/aws-secret.enc.yaml
Labels: approved, lgtm, size/XS

#137 Add read-only s3 creds to stage and fix the hive metastore dir
  trino/base/hive-config.yaml
  trino/base/hive-metastore-entrypoint.yaml
  trino/overlays/stage/aws-secret.enc.yaml
  trino/overlays/stage/kustomization.yaml
  trino/overlays/stage/trino-catalog-secret.yaml
Labels: approved, size/M

#138 Set prod values to recommended settings
  trino/overlays/prod/kustomization.yaml
Labels: approved, lgtm, size/S

#139 Add quotes in trino prod parameters
  trino/overlays/prod/kustomization.yaml
Labels: approved, lgtm, size/XS

#140 Revert S3 changes in stage and change prod S3 creds
  trino/overlays/prod/aws-secret.enc.yaml
  trino/overlays/stage/aws-secret.enc.yaml
  trino/overlays/stage/kustomization.yaml
  trino/overlays/stage/trino-catalog-secret.yaml
Labels: approved, lgtm, size/M

#141 Upgrade superset to v1.1.0
  superset/secrets.enc.yaml
  superset/templates/odh_cr.yaml
Labels: approved, lgtm, size/XS

#142 Increase retention policy for some pnc topics
  kafka/secrets.enc.yaml
Labels: approved, size/M

#143 include data-science and pytorch notebook based on python 3.8
  jupyterhub/bases/custom-images/jupyterhub-custom-images.yaml
Labels: approved, lgtm, size/M

#144 Enable SQL templating in Superset
  superset/templates/odh_cr.yaml
Labels: approved, lgtm, size/XS
