Repository AICoE/idh-manifests, pull requests merged in 2022-01, with the labels that each got.

#194 Reduce retention for busiest topics
  kafka/secrets.enc.yaml
Labels: approved, size/S, lgtm

#195 Remove the ingest.fluentd and dynamic-fluentd topics
  kafka/secrets.enc.yaml
Labels: approved, size/XS

#196 Remove Maulik from OWNERS list
  OWNERS
Labels: approved, size/XS, lgtm
